server:
  port: 9527

spring:
  application:
    name: microservicecloud-gateway-zuul

eureka:
  client:
    service-url: 
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-zuul-9527
    prefer-ip-address: true

zuul:
  # 添加统一访问前缀
  prefix: /service
  # 过滤所有服务请求
  ignored-services: '*'
  routes: 
    # 针对不同服务进行路由
    dept:
      # dept service由 /mydept/**来访问，而不是原来的/microservicecloud-dept/dept/**
      path: /mydept/**
      serviceId: microservicecloud-dept

# 提供微服务描述信息
info:
  app.name: microservicecloud
  company.name: com.zheng.springcloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  description: this is a spring cloud zuul gateway and router microservice, welcome!